name: Test Yaml

on:
  workflow_dispatch:

jobs:
  run-script:
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code.
      # This is required so the workflow can access the files within it.
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Upload the 'filtered_cars.html' file from your repo.
      # The 'path' now points to the specific file you want to upload.
      - name: Upload HTML report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: filtered-car-data
          path: filtered_cars.html

  send-notification:
    needs: run-script
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository to get the send_email.py script
      - name: Check out repository
        uses: actions/checkout@v4
        
      # Step 2: Download the HTML report artifact
      - name: Download Car Data HTML
        uses: actions/download-artifact@v4
        with:
          name: filtered-car-data-html

      # Step 3: Send the email using the Python script
      - name: Send email report
        env:
          # Set credentials and info as environment variables
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python send_email.py

